# Generated by Django 5.1.3 on 2024-11-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_detallepedido_pedido_detallepedido_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='imagen',
            field=models.URLField(default='https://placekitten.com/49/905'),
        ),
    ]
